<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" 
  xmlns:xmi="http://www.omg.org/XMI" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
  xmlns:java="java.xmi"
  xmlns:utility="http:///org/eclipse/ve/internal/cde/utility.ecore"
  xmlns:jcm="http:///org/eclipse/ve/internal/jcm.ecore"  
  xmlns:decorators="http:///org/eclipse/ve/internal/cde/decorators.ecore">
  <ecore:EPackage 
    xmi:id="jtabbedPaneVisuals.xmi" 
    nsURI="platform:/plugin/org.eclipse.ve.jfc/overrides/javax/swing/jtabbedPaneVisuals.ecore" 
    nsPrefix="jtabbedPaneVisuals"
    name="jtabbedPaneVisuals">
  
  <!-- JTabComponent is the "component" of a javax.swing.JTabbedPane. -->
	<eClassifiers xmi:type="ecore:EClass" xmi:id="JTabComponent" name="JTabComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="JTabComponent/component" name="component"
        eType="java:JavaClass java:/javax.swing#JComponent">
        <eAnnotations xsi:type="decorators:PropertyDescriptorDecorator" hidden="true"/>
        <eAnnotations xsi:type="jcm:BeanFeatureDecorator" linkType="CHILD"/>         
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="JTabComponent/tabTitle" unsettable="true" name="tabTitle"
        eType="java:JavaClass java:/java.lang#String"> 
        <eAnnotations xsi:type="decorators:PropertyDescriptorDecorator">
          <displayNameString xsi:type="utility:TranslatableString" key="JTabComponent.tabTitle" bundle="jtabbedPaneBundle"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="JTabComponent/tabTooltipText" unsettable="true" name="tabTooltipText"
        eType="java:JavaClass java:/java.lang#String">
        <eAnnotations xsi:type="decorators:PropertyDescriptorDecorator">
          <displayNameString xsi:type="utility:TranslatableString" key="JTabComponent.tabTooltipText" bundle="jtabbedPaneBundle"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="JTabComponent/tabIcon" unsettable="true" name="tabIcon"
        eType="java:JavaClass java:/javax.swing#Icon">
        <eAnnotations xsi:type="decorators:PropertyDescriptorDecorator">
          <displayNameString xsi:type="utility:TranslatableString" key="JTabComponent.tabIcon" bundle="jtabbedPaneBundle"/>
        </eAnnotations> 
      </eStructuralFeatures>
      
      <eAnnotations xsi:type="decorators:PropertySourceAdapterInformation"
        propertySourceAdapterClassname="org.eclipse.ve.jfc/org.eclipse.ve.internal.jfc.core.JTabComponentPropertySourceAdapter"/>
 
    </eClassifiers>
    
  </ecore:EPackage>
  
  <!-- Bundle used by decorators for tabTitle, tabTooltipText, tabIcon-->
  <utility:URLResourceBundle xmi:id="jtabbedPaneBundle" bundleName="JTabbedPaneVisuals">
    <bundleURLs>platform:/plugin/org.eclipse.ve.jfc/overrides/javax/swing/</bundleURLs>
  </utility:URLResourceBundle>
  
</xmi:XMI>