<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="codegenHelpers"
    nsURI="platform:/plugin/org.eclipse.ve.java.core/overrides/codegenHelpers.ecore"
    nsPrefix="codeGenHelpers">
  <eClassifiers xsi:type="ecore:EClass" xmi:id="CodeGenHelperClass" name="CodeGenHelperClass"
      eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/expDecoder" name="expDecoder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/eventDecoder" name="eventDecoder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/methodGenerator" name="methodGenerator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/visual" name="visual" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
