<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="codegenHelpers"
    nsURI="platform:/plugin/org.eclipse.ve.java.core/overrides/codegenHelpers.ecore"
    nsPrefix="codeGenHelpers">
  <eClassifiers xsi:type="ecore:EClass" xmi:id="CodeGenHelperClass" name="CodeGenHelperClass"
      eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/expDecoder" name="expDecoder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/eventDecoder" name="eventDecoder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/methodGenerator" name="methodGenerator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>

    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/modelled" name="modelled" unsettable="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>

    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/typeVisitor" name="typeVisitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/methodVisitor" name="methodVisitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/eventMethodCallBackVisitor" name="eventMethodCallBackVisitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/eventMethodVisitor" name="eventMethodVisitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/eventHandlerVisitor" name="eventHandlerVisitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/returnStmtVisitor" name="returnStmtVisitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/expressionVisitor" name="expressionVisitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/eventExpressionVisitor" name="eventExpressionVisitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="CodeGenHelperClass/eventCallBackExpressionVisitor" name="eventCallBackExpressionVisitor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
