

-- Uncomment the following statements, if the Tables are already there, and need to be recreated


--ALTER TABLE TEST.PERSON DROP FOREIGN KEY MANAGER;

--ALTER TABLE TEST.PERSON_BACKUP DROP FOREIGN KEY FKFE61DDEC426A9CB7;

--ALTER TABLE TEST.PERSON_BACKUP DROP FOREIGN KEY FKFE61DDEC247C2A44;

--ALTER TABLE TEST.SPOUSE DROP FOREIGN KEY SPOUSE;

--ALTER TABLE TEST.SPOUSE DROP FOREIGN KEY PERSON;

--DROP TABLE TEST.PERSON;

--DROP TABLE TEST.PERSON_BACKUP;

--DROP TABLE TEST.SPOUSE;

--DROP SCHEMA TEST RESTRICT;

CREATE SCHEMA TEST;

CREATE TABLE TEST.PERSON
  (FIRST_NAME VARCHAR(50) NOT NULL,
   LAST_NAME VARCHAR(50) NOT NULL,
   ID BIGINT NOT NULL,
   MANAGER BIGINT);

ALTER TABLE TEST.PERSON
  ADD CONSTRAINT ID PRIMARY KEY (ID);

CREATE TABLE TEST.PERSON_BACKUP
  (PERSON_ID BIGINT NOT NULL,
   BACKUP_ID BIGINT NOT NULL);

ALTER TABLE TEST.PERSON_BACKUP
  ADD CONSTRAINT ID PRIMARY KEY (PERSON_ID, BACKUP_ID);

CREATE TABLE TEST.SPOUSE
  (PERSON_ID BIGINT NOT NULL,
   SPOUSE_ID BIGINT NOT NULL);

ALTER TABLE TEST.SPOUSE
  ADD CONSTRAINT PERSON_ID PRIMARY KEY (PERSON_ID);

ALTER TABLE TEST.SPOUSE
  ADD CONSTRAINT UNIQUE_SPOUSE UNIQUE(SPOUSE_ID);

ALTER TABLE TEST.PERSON
  ADD CONSTRAINT MANAGER FOREIGN KEY (MANAGER)
  REFERENCES TEST.PERSON(ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE TEST.PERSON_BACKUP
  ADD CONSTRAINT FKFE61DDEC426A9CB7 FOREIGN KEY (BACKUP_ID)
  REFERENCES TEST.PERSON(ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE TEST.PERSON_BACKUP
  ADD CONSTRAINT FKFE61DDEC247C2A44 FOREIGN KEY (PERSON_ID)
  REFERENCES TEST.PERSON(ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE TEST.SPOUSE
  ADD CONSTRAINT SPOUSE FOREIGN KEY (SPOUSE_ID)
  REFERENCES TEST.PERSON(ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE TEST.SPOUSE
  ADD CONSTRAINT PERSON FOREIGN KEY (PERSON_ID)
  REFERENCES TEST.PERSON(ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;