<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    xmlns:jcm="http:///org/eclipse/ve/internal/jcm.ecore"   
    name="vcerules"
    nsURI="platform:/plugin/org.eclipse.ve.tests/resources/vcerules/vcerules.ecore" nsPrefix="org.eclipse.ve.tests.vcerules">
  <!-- Set up for PostSet tests -->
  <eClassifiers xsi:type="ecore:EClass" name="ParentContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" eType="#//Component" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refs" eType="#//Child" upperBound="-1"/>    
    <eStructuralFeatures xsi:type="ecore:EReference" name="depends" eType="#//Child" upperBound="-1">    
      <eAnnotations xsi:type="jcm:BeanFeatureDecorator" linkType="DEPENDENCY"/>
    </eStructuralFeatures>    
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Child">    
      <eAnnotations xsi:type="jcm:BeanFeatureDecorator" linkType="CHILD"/>
    </eStructuralFeatures>        
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childComponent" eType="#//Child">
      <eAnnotations xsi:type="jcm:BeanFeatureDecorator" linkType="CHILD"/>
    </eStructuralFeatures>
  </eClassifiers>
  
  <eClassifiers xsi:type="ecore:EClass" name="Child">
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossRef" eType="#//Child"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depends" eType="#//ParentContainer">
      <eAnnotations xsi:type="jcm:BeanFeatureDecorator" linkType="DEPENDENCY"/>
    </eStructuralFeatures>
  </eClassifiers>
  
  <!-- Now set up for preset tests. -->
  <eClassifiers xsi:type="ecore:EClass" name="NOLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childComponent" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="GLOBAL_GLOBALLocation">
    <eAnnotations xsi:type="jcm:BeanDecorator" beanLocation="GLOBAL_GLOBAL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childComponent" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">    
      <eAnnotations xsi:type="jcm:BeanFeatureDecorator" beanLocation="GLOBAL_GLOBAL"/>    
    </eStructuralFeatures>
  </eClassifiers>
  
  <eClassifiers xsi:type="ecore:EClass" name="GLOBAL_LOCALLocation">
    <eAnnotations xsi:type="jcm:BeanDecorator" beanLocation="GLOBAL_LOCAL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childComponent" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">    
      <eAnnotations xsi:type="jcm:BeanFeatureDecorator" beanLocation="GLOBAL_LOCAL"/>    
    </eStructuralFeatures>    
  </eClassifiers>
  
  <eClassifiers xsi:type="ecore:EClass" name="LOCALLocation">
    <eAnnotations xsi:type="jcm:BeanDecorator" beanLocation="LOCAL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childComponent" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">    
      <eAnnotations xsi:type="jcm:BeanFeatureDecorator" beanLocation="LOCAL"/>    
    </eStructuralFeatures>        
  </eClassifiers>
  
  <eClassifiers xsi:type="ecore:EClass" name="PropertyLocation">
    <eAnnotations xsi:type="jcm:BeanDecorator" beanLocation="PROPERTY"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childComponent" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">    
      <eAnnotations xsi:type="jcm:BeanFeatureDecorator" beanLocation="PROPERTY"/>    
    </eStructuralFeatures>            
  </eClassifiers>     

  <eClassifiers xsi:type="ecore:EClass" name="NOReturn">
    <eAnnotations xsi:type="jcm:BeanDecorator" beanReturn="false"/>
  </eClassifiers>     
    
</ecore:EPackage>
