<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="utility"
    nsURI="http:///org/eclipse/ve/internal/cde/utility.ecore" nsPrefix="org.eclipse.ve.internal.cde.utility">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractString" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantString" eSuperTypes="#//AbstractString">
    <eAttributes name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=" "/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceBundle" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="URLResourceBundle" eSuperTypes="#//ResourceBundle">
    <eAttributes name="bundleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="bundleURLs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graphic" abstract="true" eSuperTypes="../../org.eclipse.emf.ecore/src/model/Ecore.ecore#//EObject #//IGraphic"/>
  <eClassifiers xsi:type="ecore:EClass" name="GIFFileGraphic" eSuperTypes="#//Graphic">
    <eAttributes name="resourceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TranslatableString" eSuperTypes="#//AbstractString">
    <eReferences name="bundle" eType="#//ResourceBundle"/>
    <eAttributes name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IGraphic" instanceClassName="org.eclipse.ve.internal.cde.emf.IGraphic"
      abstract="true" interface="true"/>
</ecore:EPackage>
